#!/bin/bash
#SBATCH -p edu-thesis
#SBATCH --gres=gpu:4
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=65536M
#SBATCH -N 1
#SBATCH -t 0-5:00

# 8192M
# 32768M
# 65536M
module load cuda/11.8
source /home/diego.calanzone/.bashrc
source activate semantic_models 
cd /home/diego.calanzone/glp/hypernet

python main.py -i ../SOLA_dataset_preprocessed/my_datasets/ -o out
