#!/bin/bash
#SBATCH -p edu-thesis
#SBATCH --gres=gpu:2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16536M
#SBATCH -N 1
#SBATCH -t 0-5:00

# 8192M
# 32768M
# 65536M
module load cuda/11.8
source /home/diego.calanzone/.bashrc
source activate semantic_models 
cd /mnt/cimec-storage6/users/diego.calanzone/logical-comparative-learning

python main.py -i /mnt/cimec-storage6/shared/filippo_diego_datasets/my_datasets -o out
