#!/bin/bash
#SBATCH -p edu-thesis
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=65536
#SBATCH -N 1
#SBATCH -t 0-5:00

module load cuda/11.8
source /home/diego.calanzone/.bashrc
source activate semantic_models 
cd /home/diego.calanzone/glp/der_hypernet

python main.py -i SOLA -o out --buffer_size 10000 --wandb 1 --run_name main_der++
